development:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: smart_sos_production
  pool: 5
  timeout: 5000
