development: 
  adapter: postgresql
  host: localhost
  database: intro_to_rails_dev
  pool: 5
  timeout: 5000

test: 
  adapter: postgresql
  host: localhost
  database: intro_to_rails_test
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql
  host: localhost
  database: intro_to_rails
  pool: 5
  timeout: 5000